openapi: "3.0.0"
info:
  title: "Flask Prediction API"
  version: "1.0.0"
paths:
  /predict:
    post:
      summary: "Predict based on input variables"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                {% for i in range(1, 14) %}
                input{{i}}:
                  type: number
                {% endfor %}
      responses:
        "200":
          description: "Prediction result"
          content:
            application/json:
              schema:
                type: object
                properties:
                  prediction:
                    type: number
